name: Test SSH Connection

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up SSH key and known hosts
      - name: Set up SSH
        run: |
          # Create the SSH directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Add the private key from GitHub Secrets
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add the server to known hosts (avoids prompt during connection)
          ssh-keyscan -H ${{ secrets.SFTP_SERVER }} >> ~/.ssh/known_hosts

      # Test SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }} "echo 'SSH Connection Successful!'"
